### PR TITLE
Fix string tokenization

### LINKED ISSUE #267: getUsedVariables() throws NPE
Note: Version of EvalEx: 2.6
Custom Functions: I have also added custom functions to handle strings following this: https://github.com/uklimaschewski/EvalEx#custom-functions-with-string-parameters

Test case: Testing simple calculation and assignment expressions and for checking what values to provide from database for used variables, I make use of the getUsedVariables() method.

1.  When there is a simple assignment expression like var1=10, the correct result is computed.  In this case getUsedVariables() returns an empty list.

2.  When there is a simple assignment expression of a string like var1="somestring", then the getUsedVariables() throws a null pointer exception.  **The data here has starting double quotes and ending double quotes.  If the quotes are not there in the data then getUsedVariables() works properly.**

Stack trace:  (only 2 lines from EvalEx are printed)

```
16:32:50,154 ERROR java.lang.NullPointerException  
16:32:50,154 ERROR at com.udojava.evalex.Expression$Tokenizer.next(Expression.java:507)  
16:32:50,155 ERROR at com.udojava.evalex.Expression.getUsedVariables(Expression.java:2078)  
16:32:50,155 ERROR com.unvired.operation.CalculateRequest.calculate(CalculateRequest.java:99)  
```

If the routine is allowed to run (removing the GetUsedVariables()) call then the following NPE occurs:

```
17:04:08,413 ERROR java.lang.NullPointerException
17:04:08,484 ERROR at com.udojava.evalex.Expression$Tokenizer.next(Expression.java:507)
17:04:08,598 ERROR at com.udojava.evalex.Expression.shuntingYard(Expression.java:1342)
17:04:08,686 ERROR at com.udojava.evalex.Expression.getRPN(Expression.java:1914)
17:04:08,761 ERROR at com.udojava.evalex.Expression.eval(Expression.java:1507)
17:04:08,859 ERROR at com.unvired.operation.CalculateRequest.calculate(CalculateRequest.java:154)
```
The expectation was that the string literal would be returned.  Is this incorrect or an invalid expectation?

### PR DESCRIPTION
**Pull request by MDZhB**
Fixes #267. The tokenizer previously did not consume closing quotes in string literals until the following call to `next()`. This meant that the tokenizer always behaved as though there was more input to consume after a string literal. If the last token in an expression was a string literal, upon reaching the end of the expression `hasNext()` erroneously returned `true`, and the subsequent call to `next()` produced an empty token with type null.

This PR includes some minor refactoring of tokenizer code to make it less repetitious and easier to read. Lines that manipulate the tokenizer position and token content have been replaced with the methods `consumeChar()` and `skipChar()`. It also adds a new `TokenizerException`; this inherits from `ExpressionException` so as to not break existing exception handlers.

Note that the new string logic will change the behaviour of strings slightly: literals without closing quotation marks will cause a `TokenizerException`.

### CODE REVIEW

File: src/test/java/com/udojava/evalex/TestTokenizer.java [hunk 1]
```diff
@@ -1,15 +1,16 @@
...
 import com.udojava.evalex.Expression.TokenType;
 import java.math.BigDecimal;
 import java.util.Iterator;
+
+import org.junit.Rule;
 import org.junit.Test;
+import org.junit.function.ThrowingRunnable;
+import org.junit.rules.ExpectedException;
+
+import static org.junit.Assert.*;
```
Comment (uklimaschewski) [inline src/test/java/com/udojava/evalex/TestTokenizer.java:13]: please do not use wildcard imports

File: src/test/java/com/udojava/evalex/TestGetUsedVariables.java [hunk 2]
```diff
@@ -33,4 +35,11 @@ public void testVarsNothing() {
     List<String> usedVars = ex.getUsedVariables();
     assertEquals(0, usedVars.size());
   }
+
+  @Test
+  public void testStringComparison() {
+    // test for issue #267 (getUsedVariables() throws NPE in expressions containing string literals)
+    Expression ex = new Expression("foo=\"bar\"").setVariable("foo", (BigDecimal) null);
+    assertEquals(Arrays.asList("foo"), ex.getUsedVariables());
```
Comment (uklimaschewski) [inline src/test/java/com/udojava/evalex/TestGetUsedVariables.java:43]: replace with `Collections.singletonList("foo")`

File: src/test/java/com/udojava/evalex/TestTokenizer.java [hunk 3]
```diff
@@ -1,15 +1,16 @@
...
-import static org.junit.Assert.assertFalse;
-import static org.junit.Assert.assertNull;
-import static org.junit.Assert.assertTrue;
-
 import com.udojava.evalex.Expression.Token;
 import com.udojava.evalex.Expression.TokenType;
 import java.math.BigDecimal;
 import java.util.Iterator;
+
+import org.junit.Rule;
```
Comment (uklimaschewski) [inline src/test/java/com/udojava/evalex/TestTokenizer.java:8]: Remove unused imports (org.junit.Rule and org.junit.rules.ExpectedException)

File: src/main/java/com/udojava/evalex/TokenizerException.java [hunk 4]
```diff
@@ -0,0 +1,11 @@
+package com.udojava.evalex;
+
+public class TokenizerException extends Expression.ExpressionException {
+    public TokenizerException(String message) {
```
Comment (uklimaschewski) [inline src/main/java/com/udojava/evalex/TokenizerException.java:4]: Remove this unused constructor

**Review by uklimaschewski — CHANGES_REQUESTED** [review]

**Comment by MDZhB** [comment]
@uklimaschewski addressed your feedback, thank you.

**Comment by uklimaschewski** [comment]
Thank you for that useful PR! :-)
